"""
schemas.py — All Pydantic models for request/response validation.

WHY PYDANTIC?
  - Automatically rejects malformed input BEFORE it reaches the LLM
  - Provides clear error messages to the caller
  - Acts as living documentation of the API contract
  - Ensures output always has the exact same shape, even if LLM misbehaves

DESIGN DECISION:
  We use Optional[str] for all extracted values because any field
  may legitimately be absent from the source text. Forcing non-null
  would require us to hallucinate values — never acceptable.
"""

from typing import Optional
from pydantic import BaseModel, Field, field_validator


# ---------------------------------------------------------------------------
# REQUEST MODEL
# ---------------------------------------------------------------------------

class ExtractionRequest(BaseModel):
    """
    The body sent by the caller to POST /extract.

    We deliberately keep this minimal — just the raw text.
    The API's job is to ADD structure, not require it upfront.
    """
    text: str = Field(
        ...,                          # ... means "required"
        description="Raw unstructured text to extract fields from",
        min_length=1,                 # reject empty strings immediately
        max_length=10_000,            # prevent abuse / runaway prompts
    )

    @field_validator("text")
    @classmethod
    def text_must_not_be_blank(cls, v: str) -> str:
        """
        Extra guard: reject strings that are all whitespace.
        Pydantic's min_length=1 only checks len(), not content.
        A string like '   ' passes min_length but is useless for extraction.
        """
        if not v.strip():
            raise ValueError("text must contain non-whitespace content")
        return v.strip()          # also strip leading/trailing whitespace


# ---------------------------------------------------------------------------
# FIELD-LEVEL RESPONSE MODEL
# ---------------------------------------------------------------------------

class ExtractedField(BaseModel):
    """
    Represents a single extracted field with its confidence score.

    CONFIDENCE DESIGN:
      - Scores are generated BY the LLM, not by us
      - The LLM is instructed to be conservative (see prompts/)
      - We only apply the threshold here — we don't modify the score
      - This makes confidence scores honest, not post-hoc rationalisations

    NEEDS_REVIEW LOGIC:
      - Automatically derived from confidence vs CONFIDENCE_THRESHOLD
      - Not set by the LLM (prevents the LLM from gaming the flag)
      - Set once in the confidence engine, never overridden
    """
    value: Optional[str] = Field(
        default=None,
        description="Extracted value, or null if field was not found"
    )
    confidence: float = Field(
        ...,
        ge=0.0,                   # ge = greater than or equal
        le=1.0,                   # le = less than or equal
        description="Confidence score between 0.0 and 1.0"
    )
    needs_review: bool = Field(
        ...,
        description="True if confidence is below the 0.75 threshold"
    )


# ---------------------------------------------------------------------------
# FULL EXTRACTION RESPONSE
# ---------------------------------------------------------------------------

class ExtractionFields(BaseModel):
    """
    Container for all seven required fields.

    WHY EXPLICIT FIELDS INSTEAD OF Dict[str, ExtractedField]?
      - Guarantees all 7 fields ALWAYS appear in the response
      - A dict could omit fields if the LLM didn't return them
      - Pydantic will auto-set missing fields to their defaults
      - The OpenAPI spec (at /docs) shows exactly what to expect
    """
    vendor_name: ExtractedField
    amount:      ExtractedField
    currency:    ExtractedField
    date:        ExtractedField
    category:    ExtractedField
    description: ExtractedField
    invoice_id:  ExtractedField


class ExtractionResponse(BaseModel):
    """
    The top-level response returned by POST /extract.

    REVIEW_REQUIRED LOGIC:
      True if ANY of the seven fields has needs_review=True.
      This gives the human reviewer a single boolean to check
      rather than scanning all seven fields manually.
    """
    review_required: bool = Field(
        ...,
        description="True if any field's confidence is below 0.75"
    )
    fields: ExtractionFields


# ---------------------------------------------------------------------------
# ERROR RESPONSE (for consistent error shape)
# ---------------------------------------------------------------------------

class ErrorResponse(BaseModel):
    """
    Returned when the API cannot process the request.

    Using a consistent error shape means clients can always parse
    error responses the same way, rather than getting raw HTTP errors.
    """
    error: str = Field(..., description="Human-readable error message")
    detail: Optional[str] = Field(
        default=None,
        description="Additional technical detail, if available"
    )
